### ISSUE TITLE
Feature: MVP requirements

### ISSUE THREAD

**Issue by garrettmichaelgeorge** [samrose/ex_integrate#11]
From chat:

> I'd hope that the failure would always be due to my code, or an issue with the operating system running the command, and never if possible, because of the CI system malfunction. I would hope that the system will stop trying to build and test the software being run through the CI, and would give me back as much information as possible about which step failed, how and why.
>
> And I would hope that that the system would be able to re-run the steps again upon my either triggering it, or pushing a new commit, and if the underlying OS or my code were working well, the system should pass the build and test.
>
> The CI system should not react to the running of the steps other than to stop the build, mark it as failed, and give back to me as much info as possible
> 
> The CI system should not have logic to say "Oh! this step failed, I better try that again!" because you can imagine if you put through a test that fails for some reason, what will happen is that the test will just keep restarting in a loop, wasting computing resources on a futile effort.

A rough sketch of our requirements:

Given the ExIntegrate application and a user config that defines pipelines and steps for a CI build…

* The application should store and track information about the running of a step, including any output from that step's system command.
* A step should be easily introspect-able at any time during its lifecycle, such that theoretically, a user should be able to monitor the progress of a CI build in real-time
* The application should recognize step failures and distinguish between OS-level failures, build failures, and unanticipated ExIntegrate errors
* If a step fails:
  - The step's pipeline should cease immediately, and no further steps should be run.
  - No pipelines that depend on the failed pipeline should be run.
  - Any pipelines running concurrent to the failed pipeline should finish their steps.
  - A failure message should be shown to the user
  - Notifications should be sent to all interested parties (perhaps via pubsub?), e.g. GitHub web hooks, etc.
* If all steps pass:
  - A success message should be shown to the user.
  - Notifications should be sent to all interested parties

WDYT? @samrose

**Comment by samrose** [comment]
@garrettmichaelgeorge I think it looks really good as a description

We have a nice and performant access to streams of status via rambo https://hexdocs.pm/rambo/0.2.0/Rambo.html#module-logging 


This part

>The application should recognize step failures and distinguish between OS-level failures, build failures, and unanticipated ExIntegrate errors

I think could be made simpler in that we could just react to all the possible OS or Command errors or feedback from Rambo as one handling (the running of steps) or we could set a different error if ex_integrate errors itself. But any error for the Rambo-originated errors just stops the build. 

It's not yet totally clear how to handle ex_integrate class of errors however. We can discuss

**Comment by samrose** [comment]
closed in favor of #22
