### ISSUE TITLE
Upgrade to Elixir 1.13/OTP 24

### ISSUE THREAD

**Issue by garrettmichaelgeorge** [samrose/ex_integrate#18]
With Elixir 1.13 officially [released](https://elixir-lang.org/blog/2021/12/03/elixir-v1-13-0-released/), we might as well develop against the latest features as we move towards our own first release. I assume we would need to change `elixir.nix`, `mix.exs`, and the CircleCI config.

What do you think, @samrose?

**Comment by samrose** [comment]
@garrettmichaelgeorge thank you agree 100%

**Comment by samrose** [comment]
I’ll do this by tomorrow
